#!/bin/sh
#
# Starts hwscan
#

NAME=hwscan

fwinfo() {
	awk "/$1/ { print \$2 }" /etc/fw-info.json | tr -d '",'
}

MINER_PLATFORM=$(fwinfo platform)
HWSCAN_ARGS="--platform $MINER_PLATFORM"

start() {
	printf "Starting %s: " $NAME

	if hwscan $HWSCAN_ARGS; then
        echo "OK"
    else
        echo "FAIL"
    fi
}

case "$1" in
	start)
		"$1";;
	stop)
		exit 0;;
	*)
		echo "Usage: $0 {start}"
		exit 1
esac
