#!/usr/bin/env python3
"""Independent public genesis vector, not a captured T21 job or live share.
Data transcribed from Bitcoin Core v29.0 src/kernel/chainparams.cpp.
No vendor code or Bitcoin Core implementation is copied into this generator.
"""
from pathlib import Path
import argparse,hashlib,json,struct
ROOT=Path(__file__).resolve().parents[1]
def dsha(b):return hashlib.sha256(hashlib.sha256(b).digest()).digest()
def outputs():
    text=b'The Times 03/Jan/2009 Chancellor on brink of second bailout for banks'
    sig=bytes.fromhex('04ffff001d0104')+bytes([len(text)])+text
    pub=bytes.fromhex('04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f')
    script=bytes([len(pub)])+pub+b'\xac'
    tx=struct.pack('<I',1)+b'\x01'+bytes(32)+b'\xff'*4+bytes([len(sig)])+sig+b'\xff'*4+b'\x01'+struct.pack('<Q',5000000000)+bytes([len(script)])+script+bytes(4)
    root=dsha(tx);assert root[::-1].hex()=='4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b'
    header=struct.pack('<I',1)+bytes(32)+root+struct.pack('<III',1231006505,0x1d00ffff,2083236893)
    digest=dsha(header);assert digest[::-1].hex()=='000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f'
    words=b''.join(header[i:i+4][::-1] for i in range(0,80,4))+bytes(range(32))
    target=(0xffff<<(8*(0x1d-3))).to_bytes(32,'little')
    arrays={'coinbase':tx,'header':header,'words':words,'root':root,'hash':digest,'target':target}
    meta={'provenance':'Bitcoin Core v29.0 src/kernel/chainparams.cpp',
      'source_url':'https://github.com/bitcoin/bitcoin/blob/v29.0/src/kernel/chainparams.cpp',
      'source_blob_sha':'ac3fc9eadad6f32500697f978c7bbfc17acc183a',
      'not_a_live_share':True,'data':{k:v.hex() for k,v in arrays.items()}}
    c='/* Public historical test vector; generated by tools/generate_genesis_fixture.py. */\n#ifndef VN135_GENESIS_FIXTURE_H\n#define VN135_GENESIS_FIXTURE_H\n#include <stdint.h>\n'
    for k,v in arrays.items():
        c+=f'static const uint8_t fixture_{k}[{len(v)}] = {{\n'
        c+='\n'.join('    '+','.join('0x'+v[j:j+1].hex() for j in range(i,min(i+16,len(v))))+',' for i in range(0,len(v),16))+'\n};\n'
    c+='#endif\n'
    return {ROOT/'tests/fixtures/genesis_work.h':c,ROOT/'evidence/stage9/genesis-vector.json':json.dumps(meta,indent=2)+'\n'}
def main():
    p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');a=p.parse_args()
    for path,text in outputs().items():
        if a.write:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text)
        else:assert path.read_text()==text,path
    print('Genesis fixture: coinbase, Merkle root, serialized header and hash independently checked')
if __name__=='__main__':main()
